server:
  port: 3307

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.147.11:3306/mySofu?ServerTimezone=UTC
    username: mySofu
    password: dEedGsJmFc344sDD

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
